import {
  AlertTriangle,
  ArrowRight,
  CalendarDays,
  CalendarRange,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  TableProperties,
  Trash,
  TrendingDown,
  TrendingUp,
  User,
  User2Icon,
  UserPlus,
  UserX2Icon,
  X,
} from "lucide-react";

export const Icons = {
  dashboard: LayoutDashboardIcon,
  settings: Settings,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserPlus,
  post: FileText,
  page: File,
  media: Image,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  table: TableProperties,
  check: Check,
  calendar: CalendarDays,
  calendarRange: CalendarRange,
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
};
